module.exports = (app) => {
  const files = require("./files")
  const register = require('./register.js')
  const login = require('./login.js')
  const user = require('./user.js')
  const department = require('./department.js')
  const major = require('./major.js')
  const sector_info = require('./sector_info.js')
  const _class  = require('./class.js')
  const organization = require('./organization')
  const club = require('./club_type')
  const stu_job = require('./stu_job')
  const affiche_info = require('./affiche_info')
  const activity = require('./activity.js')
  const comment = require('./comment.js')
  
  app.use("/api", files)
  app.use("/api", register)
  app.use("/api", login)
  app.use("/api", user)
  app.use("/api", department)
  app.use("/api", sector_info)
  app.use("/api", major)
  app.use("/api", _class)
  app.use("/api", organization)
  app.use('/api', club)
  app.use('/api', stu_job)
  app.use('/api', affiche_info)
  app.use('/api', activity)
  app.use('/api', comment)
};